### ISSUE TITLE
Module always exits with exit code "1"

### ISSUE THREAD

**Issue by MarcRiera** [apertium/apertium-anaphora#32]
The program seems to be exiting with code "1" regardless of the situation. With blank input, it exits with code "1", and with correct Apertium input, it finds the correct referents and adds them in the output, yet still exits with code "1". If no problem is found, the module should be exiting with code "0".

Thanks!

**Comment by khannatanmai** [comment]
@MarcRiera thanks for pointing this out!
I changed the default exit to 1 and if there's an error it returns with 0. (Although it doesn't have very sophisticated error handling yet, i.e. it still assumes that the stream given from the previous module in the pipeline is the correct Apertium-stream format)

https://github.com/apertium/apertium-anaphora/commit/488a6fc3fe21332078aee150894071b300e5a219

**Comment by unhammer** [comment]
>  default exit to 1 and if there's an error it returns with 0

other way around, right? (In Unix, 0 is success, and anything above 0 is failure, [because there are so many ways things can go wrong and so few ways in which they can go right](https://en.wikipedia.org/wiki/Anna_Karenina_principle).)

**Comment by khannatanmai** [comment]
@unhammer that is the convention I was aware of too but I thought maybe there's a difference convention here?

What's the final one? I'll change it to that.

**Comment by unhammer** [comment]
0: no error

1 (or anything over 1): error

**Comment by MarcRiera** [comment]
@khannatanmai Thanks for looking into this!

**Comment by khannatanmai** [comment]
@unhammer I just realised, I changed it to 0 for no error only that was a typo in my earlier comment. Yep, it's 0 for no error :)

**Comment by khannatanmai** [comment]
@MarcRiera Thanks for pointing it out :)
