### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by khannatanmai** [apertium/apertium-anaphora#34]
- [x] Catalan-Italian (Done by @hectoralos)
- [x] Spanish-English (Done)
- [ ] Kir-Eng

https://drive.google.com/file/d/18MSisDqrq0DDAHhzTkuBcsj9INURJu50/view

**Comment by ashiscs** [comment]
Can anyone tell me how to start contributing?

**Comment by unhammer** [comment]
Not here. See http://wiki.apertium.org/wiki/Contributing
