### ISSUE TITLE
Package version empty

### ISSUE THREAD

**Issue by MarcRiera** [apertium/apertium-anaphora#37]
The apertium-anaphora package is currently released as version 0.0.2. However, the version number must be missing somewhere, because it shows up as empty when installed and makes pairs depending on it unable to fulfil requirements. An example can be found here (Travis build of apertium-eng-cat): https://travis-ci.com/apertium/apertium-eng-cat/builds/131180804

Doing ```make install``` results in the same problem.

**Comment by TinoDidriksen** [comment]
Fixed in https://github.com/apertium/apertium-anaphora/commit/a87009d5503c027902576796907aa60ff38bc2d9
