### ISSUE TITLE
Should error if arx is bad or missing

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-anaphora#39]
````
echo 'water' | apertium eng-cat && echo "good"
I/O warning : failed to load external entity "/usr/share/apertium/apertium-eng-cat/apertium-eng-cat.eng-cat.arx"
Document not parsed successfully.
aigua
good
````

This should be an error, not a warning. If the required file is missing or invalid, error out so we catch it in tests.

**Comment by khannatanmai** [comment]
I make it exit if parsed incorrectly, in b1e97ac519bb319120e723385de9d7b98ff2470c .
Is that what you were referring to? Or the fact that it says I/O warning? Because that's a warning from the libxml parser.

**Comment by TinoDidriksen** [comment]
That looks like what I want. The warning is harmless, but if the ARX wasn't loaded correctly or was invalid then the whole process should just die with an error.

**Comment by khannatanmai** [comment]
Yeah, I made it return earlier, I just forgot to make the thing exit. 
Closing :)
