### ISSUE TITLE
Change build system to autotools

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-anaphora#42]
To fit in with the rest of the Apertium ecosystem.

**Comment by TinoDidriksen** [comment]
I would vastly prefer turning all the C++ packages to CMake, to make it easier work with IDEs and debuggers and to build on Windows with VC++ and vcpkg. autotools is just horrendous to work with cross-platform.

**Comment by ftyers** [comment]
I find CMake pretty horrendous to work with and prefer the build systems to be uniform across the project. You already work with apertium, lttoolbox, separable and lex-tools with autotools, let alone all of the language packages. If you want to work with CMake you can always maintain a branch `cmake-build`.

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-anaphora/commit/a3964ec8fa826df7b04115474e355620bb9bee49
